const BINGO_PROMPTS = [
    "Loves music",
    "Has a pet",
    "Can sing",
    "Plays an instrument",
    "Speaks 2+ languages",
    "Traveled to 3+ countries",
    "Is a morning person",
    "Is a night owl",
    "Likes spicy food",
    "Prefers tea over coffee",
    "Has a tattoo",
    "Can cook a signature dish",
    "Loves horror movies",
    "Is an only child",
    "Has 3+ siblings",
    "Born in another city",
    "Wearing blue today",
    "Has green eyes",
    "Left-handed",
    "Met a celebrity",
    "Can whistle a tune",
    "Can ride a motorcycle",
    "Loves gardening",
    "Has a hidden talent",
    "Regularly goes to the gym",
    "Likes to hike",
    "Is a bookworm",
    "Loves video games",
    "Can do a magic trick",
    "Has run a marathon",
    "Owns a vintage item",
    "Can dance salsa",
    "Prefers winter over summer",
    "Has a collection (stamps, coins, etc.)",
    "Always carries a water bottle",
    "Has bungee jumped",
    "Loves to paint or draw",
    "Is good at chess",
    "Has a lucky charm",
    "Likes to bake",
    "Been to a music festival",
    "Can solve a Rubik's cube",
    "Loves camping",
    "Watched a whole series in one day",
    "Has a reusable straw",
    "Can name all 7 continents",
    "Has a birthday this month",
    "Doesn't like chocolate",
    "Has a master's degree",
    "Is wearing a watch",
    "Can swim long distances",
    "Owns a plant they haven't killed",
    "Knows how to knit or crochet"
];

// Exporting for use in other scripts
if (typeof module !== 'undefined' && module.exports) {
    module.exports = BINGO_PROMPTS;
}
